name: Pipeline
on:
  workflow_dispatch:
    inputs:
      text_in:
        default: 'John John'
        required: false
        type: string
      number_in:
        required: true
        type: number
      

jobs:
  step1:
    uses: leonardo-tx/teste/.github/workflows/step1.yml
    with:
      text_in: ${{ inputs.text_in }}
      number_in: ${{ inputs.number_in }}
