name: Pipeline
on:
  workflow_dispatch:

jobs:
  step1:
    uses: ./.github/workflows/step1.yml
    with:
      text_in: ${{ secrets.TEXT_IN_SECRET }}
      number_in: ${{ fromJson(secrets.NUMBER_IN_SECRET) }}
  step2:
    needs: step1
    uses: ./.github/workflows/step2.yml
    with:
      text_in: ${{ needs.step1.outputs.text_out }}
      number_in: ${{ fromJson(needs.step1.outputs.number_out) }}
  step3:
    needs: step2
    uses: ./.github/workflows/step3.yml
    with:
      text_in: ${{ needs.step2.outputs.text_out }}
      number_in: ${{ fromJson(needs.step2.outputs.number_out) }}
  step4:
      needs: step3
      uses: ./.github/workflows/step4.yml
      with:
        text_in: ${{ needs.step3.outputs.text_out }}
        number_in: ${{ fromJson(needs.step3.outputs.number_out) }}

