name: Pipeline
on:
  workflow_dispatch:
    inputs:
      text_in:
        default: 'John John'
        required: false
        type: string
      number_in:
        default: '4'
        required: false
        type: string
      

jobs:
  step1:
    uses: ./.github/workflows/step1.yml
    with:
      text_in: ${{ inputs.text_in }}
      number_in: ${{ inputs.number_in }}
  step2:
    needs: step1
    uses: ./.github/workflows/step2.yml
    with:
      text_in: ${{ needs.step1.outputs.text_out }}
      number_in: ${{ needs.step1.outputs.number_out }}
