name: W2
on:
  workflow_call:
    inputs:
      text_in:
        default: 'John John'
        required: false
        type: string
      number_in:
        required: true
        type: number
    outputs:
      text_out:
        value: ${{ jobs.body_transform.outputs.text_out }}
      number_out:
        value: ${{ jobs.body_transform.outputs.number_out }}
      

jobs:
  body_transform:
    runs-on: ubuntu-latest
    outputs:
      text_out: ${{ steps.calc.outputs.text_out }}
      number_out: ${{ steps.calc.outputs.number_out }}
    steps:
      - id: calc
        shell: bash
        run: |
          TEXT="${{ inputs.text_in }}"
          NUMBE=${{ inputs.number_in }}
          NEW_TEXT="${TEXT}-${NUMBE}"
          NEW_NUMBE=$((NUMBE * 2))
          
          echo "text_out=$NEW_TEXT" >> "$GITHUB_OUTPUT"
          echo "number_out=$NEW_NUMBE" >> "$GITHUB_OUTPUT"
