name: W1
on:
  workflow_call:
    inputs:
      text_in:
        default: 'John John'
        required: false
        type: string
      number_in:
        required: true
        type: number
  workflow_dispatch:
    inputs:
      text_in:
        default: 'John John'
        required: false
        type: string
      number_in:
        required: true
        type: number

jobs:
  body_transform:
    runs-on: ubuntu-latest
    steps:
      - id: calc
        shell: bash
        run: |
          TEXT="${{ inputs.text_in }}"
          NUMBE=${{ inputs.number_in }}
          NEW_TEXT="${TEXT}-${NUMBE}"
          NEW_NUMBE=$((NUMBE * 2))
          
          echo $NEW_TEXT
          echo $NEW_NUMBE
    
