name: W1
on:
  workflow_call:
    outputs:
      text_out:
        value: ${{ jobs.body_transform.outputs.text_out }}
      number_out:
        value: ${{ jobs.body_transform.outputs.number_out }}
      

jobs:
  body_transform:
    runs-on: ubuntu-latest
    outputs:
      text_out: ${{ steps.calc.outputs.text_out }}
      number_out: ${{ steps.calc.outputs.number_out }}
    steps:
      - id: calc
        shell: bash
        run: |
          TEXT="${{ secrets.TEXT_IN_SECRET }}"
          NUMBE=${{ secrets.N_IN_SECRET }}
          NEW_TEXT="${TEXT}-${NUMBE}"
          NEW_NUMBE=$((NUMBE))
          
          echo "text_out=$NEW_TEXT" >> "$GITHUB_OUTPUT"
          echo "number_out=$NEW_NUMBE" >> "$GITHUB_OUTPUT"
